import { ExcavationStage, ProjectSettings, SoilLayer, StrutTier, WallSection } from '../types';

export interface ProjectPreset {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  description: string;
  settings: ProjectSettings;
  layers: SoilLayer[];
  wall: WallSection;
  struts: StrutTier[];
  stages: ExcavationStage[];
}

export const PRESET_PROJECTS: ProjectPreset[] = [
  {
    id: 'attached_boq_spec_station',
    title: '현장 내역서 기준 단면 (H-300×305 엄지말뚝 + H-300×305 버팀보 + 1000kN 스크류잭)',
    subtitle: 'H-300×305×15×15(SM355) + 2H-300×305 띠장 + 목재/강재토류판 (내역서 100% 일치)',
    category: '현장 내역서 적용',
    description: '첨부 공사비 내역서의 실 자재 규격(H-300×305 SM355 엄지말뚝, D500mm 천공/되메우기, 2H-300×305 띠장, H-300×305 버팀보 한면제작, 1000kN 스크류잭, K-1 화타쐐기, F-1 ㄷ-380×100, G-2 L-90×90 가새, 토류판 T=6cm/T=1.2mm)을 100% 반영한 지하 3층 개착공사 안정성 해석 모델입니다.',
    settings: {
      projectName: '도시철도 본선 지하정거장 개착공사 (내역서 자재 규격)',
      stationName: '중앙정거장 본체 가시설',
      location: '서울/수도권 도로개착 본선구간 (D500mm 천공/1000kN 스크류잭)',
      roadWidth: 32.0,
      stationWidth: 20.0,
      stationLength: 100.0,
      finalExcavationDepth: 22.0,
      storyCount: 2,
      structureHeight: 14.5,
      topCoverDepth: 7.5,
      groundWaterTable: 4.5,
      surchargeLoad: 12.0,
      earthPressureTheory: 'PECK',
      seismicCoefficient: 0.12,
      deckHouseLoad: 5.0,
      utilities: [
        { id: 'util-gas', name: '도시가스관 (D300)', type: 'GAS', depth: 3.2, offsetFromWall: 2.5, diameterMm: 300, color: '#eab308' },
        { id: 'util-water', name: '상수도 본관 (D500)', type: 'WATER', depth: 3.8, offsetFromWall: 6.5, diameterMm: 500, color: '#0284c7' },
        { id: 'util-telecom', name: '통신 광케이블 (D150)', type: 'TELECOM', depth: 3.0, offsetFromWall: 13.5, diameterMm: 150, color: '#10b981' },
        { id: 'util-power', name: '한전 지중전력구 (D250)', type: 'POWER', depth: 4.5, offsetFromWall: 17.0, diameterMm: 250, color: '#ef4444' },
      ],
    },
    layers: [
      {
        id: 'boq-l1',
        name: '매립토층 (Fill)',
        type: 'fill',
        depthTop: 0,
        depthBottom: 3.0,
        unitWeight: 18.0,
        satUnitWeight: 19.0,
        cohesion: 5,
        frictionAngle: 28,
        subgradeReactionKh: 15000,
        permeabilityK: 1e-3,
        color: '#D7CCC8',
        nValue: 8,
      },
      {
        id: 'boq-l2',
        name: '퇴적점성토 (Clay)',
        type: 'clay',
        depthTop: 3.0,
        depthBottom: 7.5,
        unitWeight: 17.5,
        satUnitWeight: 18.5,
        cohesion: 30,
        frictionAngle: 10,
        subgradeReactionKh: 9000,
        permeabilityK: 1e-6,
        color: '#B0BEC5',
        nValue: 7,
      },
      {
        id: 'boq-l3',
        name: '퇴적사질토 (Sand)',
        type: 'sand',
        depthTop: 7.5,
        depthBottom: 13.0,
        unitWeight: 19.0,
        satUnitWeight: 20.0,
        cohesion: 0,
        frictionAngle: 33,
        subgradeReactionKh: 28000,
        permeabilityK: 5e-3,
        color: '#FFE082',
        nValue: 25,
      },
      {
        id: 'boq-l4',
        name: '풍화토층 (Weathered Soil)',
        type: 'weathered_soil',
        depthTop: 13.0,
        depthBottom: 18.0,
        unitWeight: 19.5,
        satUnitWeight: 20.5,
        cohesion: 18,
        frictionAngle: 32,
        subgradeReactionKh: 40000,
        permeabilityK: 1e-4,
        color: '#BCAAA4',
        nValue: 35,
      },
      {
        id: 'boq-l5',
        name: '풍화암층 (Weathered Rock)',
        type: 'weathered_rock',
        depthTop: 18.0,
        depthBottom: 25.0,
        unitWeight: 21.5,
        satUnitWeight: 22.5,
        cohesion: 45,
        frictionAngle: 37,
        subgradeReactionKh: 80000,
        permeabilityK: 1e-5,
        color: '#8D6E63',
        nValue: 50,
      },
      {
        id: 'boq-l6',
        name: '연암층 (Soft Rock)',
        type: 'soft_rock',
        depthTop: 25.0,
        depthBottom: 35.0,
        unitWeight: 23.5,
        satUnitWeight: 24.5,
        cohesion: 120,
        frictionAngle: 42,
        subgradeReactionKh: 180000,
        permeabilityK: 1e-6,
        color: '#546E7A',
        nValue: 50,
      },
    ],
    wall: {
      type: 'H_PILE_TIMBER',
      name: 'H-300×305×15×15 (SM355) - 내역서 표준 엄지말뚝',
      totalLength: 28.0,
      embedmentDepth: 6.0,
      pileSpacing: 1.5,
      elasticModulusE: 205000,
      momentOfInertiaI: 22400, // cm4
      sectionModulusZ: 1470, // cm³
      crossSectionAreaA: 134.8, // cm²
      allowableBendingStress: 210, // MPa (SM355)
      allowableShearStress: 120, // MPa
      corrosionAllowance: 1.0,
      description: '내역서 194.092 ton 1년 사용료, 천공경 D500mm, 박기/뽑기/두부정리 적용 규격',
    },
    struts: [
      {
        id: 'boq-strut-1',
        tier: 1,
        depth: 2.0,
        type: 'H_BEAM',
        specName: 'H-300×305×15×15 버팀보 (SM355)',
        horizontalSpacing: 4.0,
        excavationWidth: 20.0,
        hasCenterPost: true,
        preloadTon: 25.0,
        crossSectionAreaA: 134.8,
        momentOfInertiaI: 22400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×305×15×15 (2련 띠장)',
        waleZ: 2940,
        waleAllowableBending: 210,
        installedAtStep: 2,
      },
      {
        id: 'boq-strut-2',
        tier: 2,
        depth: 6.5,
        type: 'H_BEAM',
        specName: 'H-300×305×15×15 버팀보 (SM355)',
        horizontalSpacing: 4.0,
        excavationWidth: 20.0,
        hasCenterPost: true,
        preloadTon: 35.0,
        crossSectionAreaA: 134.8,
        momentOfInertiaI: 22400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×305×15×15 (2련 띠장)',
        waleZ: 2940,
        waleAllowableBending: 210,
        installedAtStep: 4,
      },
      {
        id: 'boq-strut-3',
        tier: 3,
        depth: 11.0,
        type: 'H_BEAM',
        specName: 'H-300×305×15×15 버팀보 (SM355)',
        horizontalSpacing: 4.0,
        excavationWidth: 20.0,
        hasCenterPost: true,
        preloadTon: 45.0,
        crossSectionAreaA: 134.8,
        momentOfInertiaI: 22400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×305×15×15 (2련 띠장)',
        waleZ: 2940,
        waleAllowableBending: 210,
        installedAtStep: 6,
      },
      {
        id: 'boq-strut-4',
        tier: 4,
        depth: 15.5,
        type: 'H_BEAM',
        specName: 'H-300×305×15×15 버팀보 (SM355)',
        horizontalSpacing: 4.0,
        excavationWidth: 20.0,
        hasCenterPost: true,
        preloadTon: 50.0,
        crossSectionAreaA: 134.8,
        momentOfInertiaI: 22400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×305×15×15 (2련 띠장)',
        waleZ: 2940,
        waleAllowableBending: 210,
        installedAtStep: 8,
      },
      {
        id: 'boq-strut-5',
        tier: 5,
        depth: 19.5,
        type: 'H_BEAM',
        specName: 'H-300×305×15×15 버팀보 (SM355)',
        horizontalSpacing: 4.0,
        excavationWidth: 20.0,
        hasCenterPost: true,
        preloadTon: 55.0,
        crossSectionAreaA: 134.8,
        momentOfInertiaI: 22400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×305×15×15 (2련 띠장)',
        waleZ: 2940,
        waleAllowableBending: 210,
        installedAtStep: 10,
      },
    ],
    stages: [
      {
        step: 0,
        name: '초기상태 (복공판 및 H-Pile 엄지말뚝 시공)',
        excavationDepth: 0.0,
        activeStrutIds: [],
        description: '지하수위 GL -4.5m, D500mm 천공 후 H-300×305×15×15(SM355) 엄지말뚝 매설 및 도로복공판 설치',
        isCompleted: false,
      },
      {
        step: 1,
        name: '1차 굴착 (GL -2.5m, 캔틸레버)',
        excavationDepth: 2.5,
        activeStrutIds: [],
        description: '1단 띠장(2H-300×305) 및 버팀보 설치 심도까지 토류판(T=6cm) 거치하며 굴착',
        isCompleted: false,
      },
      {
        step: 2,
        name: '1단 지보공 설치 및 Preload 재하 (GL -2.0m)',
        excavationDepth: 2.5,
        activeStrutIds: ['boq-strut-1'],
        description: '1단 2H-300×305 띠장(C-1 연결, O-1 보걸이) + H-300×305 버팀보(스크류잭 1000kN) 설치 후 25tonf 선하중 재하',
        isCompleted: false,
      },
      {
        step: 3,
        name: '2차 굴착 (GL -7.0m)',
        excavationDepth: 7.0,
        activeStrutIds: ['boq-strut-1'],
        description: '2단 지보 설치 심도까지 굴착 진행 및 지하수위 강하 (차수그라우팅 D1000 연계)',
        isCompleted: false,
      },
      {
        step: 4,
        name: '2단 지보공 설치 및 Preload 재하 (GL -6.5m)',
        excavationDepth: 7.0,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2'],
        description: '2단 2H-300×305 띠장 + H-300×305 버팀보 설치 및 Preload 35tonf 재하',
        isCompleted: false,
      },
      {
        step: 5,
        name: '3차 굴착 (GL -11.5m)',
        excavationDepth: 11.5,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2'],
        description: '3단 지보 설치 심도까지 굴착 진행, 중간말뚝(ㄷ-380/L-90 가새) 지지',
        isCompleted: false,
      },
      {
        step: 6,
        name: '3단 지보공 설치 및 Preload 재하 (GL -11.0m)',
        excavationDepth: 11.5,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2', 'boq-strut-3'],
        description: '3단 H-300×305 버팀보(B-4 보강) 및 2H-300 띠장 설치 후 Preload 45tonf 재하',
        isCompleted: false,
      },
      {
        step: 7,
        name: '4차 굴착 (GL -16.0m)',
        excavationDepth: 16.0,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2', 'boq-strut-3'],
        description: '풍화토/풍화암 경계부 굴착 진행, 토류판 및 배수 관리',
        isCompleted: false,
      },
      {
        step: 8,
        name: '4단 지보공 설치 및 Preload 재하 (GL -15.5m)',
        excavationDepth: 16.0,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2', 'boq-strut-3', 'boq-strut-4'],
        description: '4단 H-300×305 버팀보 설치 및 Preload 50tonf 재하',
        isCompleted: false,
      },
      {
        step: 9,
        name: '5차 굴착 (GL -20.0m)',
        excavationDepth: 20.0,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2', 'boq-strut-3', 'boq-strut-4'],
        description: '5단 지보 심도까지 굴착 진행, 지반 융기(Heaving) 및 수동토압 모니터링',
        isCompleted: false,
      },
      {
        step: 10,
        name: '5단 지보공 설치 및 최종 바닥 굴착 (GL -22.0m)',
        excavationDepth: 22.0,
        activeStrutIds: ['boq-strut-1', 'boq-strut-2', 'boq-strut-3', 'boq-strut-4', 'boq-strut-5'],
        description: '5단 H-300×305 버팀보(55tonf) 설치 후 최종 정거장 바닥면 GL -22.0m 정지 및 기초 콘크리트 타설 준비',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'standard_subway_3f',
    title: '도심지 간선도로 하부 지하 3층 정거장 (표준 단면)',
    subtitle: 'H-Pile + 토류판 + 5단 원형강관 버팀보 (심도 24.0m, 폭 22.0m)',
    category: '지하철 표준형',
    description: '서울 및 수도권 도시철도 개착구간에서 가장 널리 적용되는 H-400×400 엄지말뚝과 Φ609.6×12t 원형강관 지보공 시스템입니다. 도로 복공판 상재하중(12 kN/m²)과 지하수위(GL -5.0m)를 반영한 6단계 굴착 공정입니다.',
    settings: {
      projectName: '수도권 도시철도 0호선 000정거장 개착공사',
      stationName: '도심중앙역 (지하 3층 본체구조물)',
      location: '서울시 강남구 테헤란로 8차선 도로 하부',
      roadWidth: 35.0,
      stationWidth: 22.0,
      stationLength: 150.0,
      finalExcavationDepth: 24.0,
      groundWaterTable: 5.0,
      surchargeLoad: 12.0,
      earthPressureTheory: 'PECK',
      seismicCoefficient: 0.12,
      deckHouseLoad: 5.0,
    },
    layers: [
      {
        id: 'layer-1',
        name: '매립층 (Fill)',
        type: 'fill',
        depthTop: 0,
        depthBottom: 3.5,
        unitWeight: 18.0,
        satUnitWeight: 19.0,
        cohesion: 5,
        frictionAngle: 28,
        subgradeReactionKh: 12000,
        permeabilityK: 1e-3,
        color: '#D7CCC8',
        nValue: 8,
      },
      {
        id: 'layer-2',
        name: '퇴적점토/실트층 (Alluvial Clay)',
        type: 'clay',
        depthTop: 3.5,
        depthBottom: 8.0,
        unitWeight: 17.5,
        satUnitWeight: 18.5,
        cohesion: 28,
        frictionAngle: 12,
        subgradeReactionKh: 8000,
        permeabilityK: 1e-6,
        color: '#B0BEC5',
        nValue: 6,
      },
      {
        id: 'layer-3',
        name: '퇴적모래/자갈층 (Alluvial Sand)',
        type: 'sand',
        depthTop: 8.0,
        depthBottom: 14.0,
        unitWeight: 19.0,
        satUnitWeight: 20.0,
        cohesion: 0,
        frictionAngle: 33,
        subgradeReactionKh: 25000,
        permeabilityK: 5e-3,
        color: '#FFE082',
        nValue: 24,
      },
      {
        id: 'layer-4',
        name: '풍화토층 (Weathered Soil)',
        type: 'weathered_soil',
        depthTop: 14.0,
        depthBottom: 20.0,
        unitWeight: 19.5,
        satUnitWeight: 20.5,
        cohesion: 15,
        frictionAngle: 32,
        subgradeReactionKh: 35000,
        permeabilityK: 1e-4,
        color: '#BCAAA4',
        nValue: 35,
      },
      {
        id: 'layer-5',
        name: '풍화암층 (Weathered Rock)',
        type: 'weathered_rock',
        depthTop: 20.0,
        depthBottom: 28.0,
        unitWeight: 21.0,
        satUnitWeight: 22.0,
        cohesion: 40,
        frictionAngle: 36,
        subgradeReactionKh: 70000,
        permeabilityK: 1e-5,
        color: '#8D6E63',
        nValue: 50,
      },
      {
        id: 'layer-6',
        name: '연암층 (Soft Rock)',
        type: 'soft_rock',
        depthTop: 28.0,
        depthBottom: 38.0,
        unitWeight: 23.0,
        satUnitWeight: 24.0,
        cohesion: 100,
        frictionAngle: 40,
        subgradeReactionKh: 150000,
        permeabilityK: 1e-6,
        color: '#546E7A',
        nValue: 50,
      },
    ],
    wall: {
      type: 'H_PILE_TIMBER',
      name: 'H-400×400×13×21 엄지말뚝 (SM355)',
      totalLength: 30.0,
      embedmentDepth: 6.0,
      pileSpacing: 1.5,
      elasticModulusE: 205000,
      momentOfInertiaI: 66600, // cm4
      sectionModulusZ: 3330, // cm³
      crossSectionAreaA: 218.7, // cm²
      allowableBendingStress: 210, // MPa
      allowableShearStress: 120, // MPa
      corrosionAllowance: 1.0,
      description: '도심지 개착 흙막이 표준 엄지말뚝 + 두께 80mm 목재/콘크리트 토류판',
    },
    struts: [
      {
        id: 'strut-1',
        tier: 1,
        depth: 2.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×12t (STK490)',
        horizontalSpacing: 4.0,
        excavationWidth: 22.0,
        hasCenterPost: true,
        preloadTon: 15.0,
        crossSectionAreaA: 225.3,
        momentOfInertiaI: 99400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-350×350×12×19',
        waleZ: 4600,
        waleAllowableBending: 210,
        installedAtStep: 2,
      },
      {
        id: 'strut-2',
        tier: 2,
        depth: 6.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×12t (STK490)',
        horizontalSpacing: 4.0,
        excavationWidth: 22.0,
        hasCenterPost: true,
        preloadTon: 25.0,
        crossSectionAreaA: 225.3,
        momentOfInertiaI: 99400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-350×350×12×19',
        waleZ: 4600,
        waleAllowableBending: 210,
        installedAtStep: 4,
      },
      {
        id: 'strut-3',
        tier: 3,
        depth: 11.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×14t (STK490)',
        horizontalSpacing: 4.0,
        excavationWidth: 22.0,
        hasCenterPost: true,
        preloadTon: 35.0,
        crossSectionAreaA: 262.0,
        momentOfInertiaI: 114000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 6,
      },
      {
        id: 'strut-4',
        tier: 4,
        depth: 16.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×14t (STK490)',
        horizontalSpacing: 4.0,
        excavationWidth: 22.0,
        hasCenterPost: true,
        preloadTon: 40.0,
        crossSectionAreaA: 262.0,
        momentOfInertiaI: 114000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 8,
      },
      {
        id: 'strut-5',
        tier: 5,
        depth: 21.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×16t (STK490)',
        horizontalSpacing: 4.0,
        excavationWidth: 22.0,
        hasCenterPost: true,
        preloadTon: 45.0,
        crossSectionAreaA: 298.3,
        momentOfInertiaI: 128000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 10,
      },
    ],
    stages: [
      {
        step: 0,
        name: '초기상태 (복공판 및 엄지말뚝 시공)',
        excavationDepth: 0.0,
        activeStrutIds: [],
        description: '지하수위 GL -5.0m, 도로상부 복공판 및 H-Pile 30.0m 시공 완료',
        isCompleted: false,
      },
      {
        step: 1,
        name: '1차 굴착 (GL -2.5m)',
        excavationDepth: 2.5,
        activeStrutIds: [],
        description: '도로 복공판 하부 1단 띠장 설치 높이까지 캔틸레버 상태 굴착 진행',
        isCompleted: false,
      },
      {
        step: 2,
        name: '1단 띠장 및 버팀보 가설 (GL -2.0m)',
        excavationDepth: 2.5,
        activeStrutIds: ['strut-1'],
        description: '1단 띠장(2H-350) 및 Φ609.6 강관 버팀보 설치 후 Preload 15ton 재하',
        isCompleted: false,
      },
      {
        step: 3,
        name: '2차 굴착 (GL -7.0m)',
        excavationDepth: 7.0,
        activeStrutIds: ['strut-1'],
        description: '지하수위(GL -5.0m) 통과, 2단 지보 설치 깊이 하부까지 굴착',
        isCompleted: false,
      },
      {
        step: 4,
        name: '2단 띠장 및 버팀보 가설 (GL -6.5m)',
        excavationDepth: 7.0,
        activeStrutIds: ['strut-1', 'strut-2'],
        description: '2단 띠장 및 버팀보 설치, Preload 25ton 유압잭 긴장 완료',
        isCompleted: false,
      },
      {
        step: 5,
        name: '3차 굴착 (GL -12.0m)',
        excavationDepth: 12.0,
        activeStrutIds: ['strut-1', 'strut-2'],
        description: '퇴적모래층 굴착, 양수펌프 가동으로 굴착면 하부 배수 유지',
        isCompleted: false,
      },
      {
        step: 6,
        name: '3단 띠장 및 버팀보 가설 (GL -11.5m)',
        excavationDepth: 12.0,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3'],
        description: '3단 지보 가설 및 Preload 35ton 재하, 벽체 휨모멘트 억제',
        isCompleted: false,
      },
      {
        step: 7,
        name: '4차 굴착 (GL -17.0m)',
        excavationDepth: 17.0,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3'],
        description: '풍화토층 통과 굴착, 4단 버팀보 설치면 확보',
        isCompleted: false,
      },
      {
        step: 8,
        name: '4단 띠장 및 버팀보 가설 (GL -16.5m)',
        excavationDepth: 17.0,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3', 'strut-4'],
        description: '4단 지보 가설 및 Preload 40ton 재하',
        isCompleted: false,
      },
      {
        step: 9,
        name: '5차 굴착 (GL -21.5m)',
        excavationDepth: 21.5,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3', 'strut-4'],
        description: '풍화암층 출현, 굴착 효율 및 지반 안정성 확인',
        isCompleted: false,
      },
      {
        step: 10,
        name: '5단 띠장 및 버팀보 가설 (GL -21.0m)',
        excavationDepth: 21.5,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3', 'strut-4', 'strut-5'],
        description: '최하단 5단 버팀보 가설 및 Preload 45ton 재하',
        isCompleted: false,
      },
      {
        step: 11,
        name: '최종 바닥 굴착 완료 (GL -24.0m)',
        excavationDepth: 24.0,
        activeStrutIds: ['strut-1', 'strut-2', 'strut-3', 'strut-4', 'strut-5'],
        description: '정거장 기초 저판(Mat Slab) 시공 깊이 GL -24.0m 최종 굴착 및 바닥 정리',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'gtx_deep_slurry_wall',
    title: '수도권 GTX 대심도 환승역사 (대구경 지보)',
    subtitle: '지하연속벽(Slurry Wall 800mm) + 6단 대형 버팀보 (심도 32.0m, 폭 26.0m)',
    category: '대심도 GTX형',
    description: '심도 30m 이상의 대심도 철도 정거장으로 높은 토압과 수압을 지지하기 위해 강성이 큰 지하연속벽(Diaphragm Wall)을 영구 벽체 겸용으로 적용하고 대구경 강관 버팀보를 6단 배치한 고난이도 단면입니다.',
    settings: {
      projectName: '광역급행철도(GTX) 00역사 개착공사',
      stationName: '대심도 환승역사',
      location: '도심 환승역세권 도로',
      roadWidth: 40.0,
      stationWidth: 26.0,
      stationLength: 165.0,
      finalExcavationDepth: 32.0,
      groundWaterTable: 3.5,
      surchargeLoad: 15.0,
      earthPressureTheory: 'PECK',
      seismicCoefficient: 0.15,
      deckHouseLoad: 6.0,
    },
    layers: [
      {
        id: 'l1',
        name: '매립토 (Fill)',
        type: 'fill',
        depthTop: 0,
        depthBottom: 4.0,
        unitWeight: 18.0,
        satUnitWeight: 19.0,
        cohesion: 5,
        frictionAngle: 28,
        subgradeReactionKh: 15000,
        permeabilityK: 1e-3,
        color: '#D7CCC8',
        nValue: 10,
      },
      {
        id: 'l2',
        name: '연약 실트점토 (Soft Silty Clay)',
        type: 'clay',
        depthTop: 4.0,
        depthBottom: 11.0,
        unitWeight: 17.0,
        satUnitWeight: 18.0,
        cohesion: 35,
        frictionAngle: 10,
        subgradeReactionKh: 7000,
        permeabilityK: 1e-6,
        color: '#90A4AE',
        nValue: 4,
      },
      {
        id: 'l3',
        name: '충적모래자갈 (Sand & Gravel)',
        type: 'sand',
        depthTop: 11.0,
        depthBottom: 18.0,
        unitWeight: 19.5,
        satUnitWeight: 20.5,
        cohesion: 0,
        frictionAngle: 35,
        subgradeReactionKh: 30000,
        permeabilityK: 1e-2,
        color: '#FFE082',
        nValue: 28,
      },
      {
        id: 'l4',
        name: '풍화암 (Weathered Rock)',
        type: 'weathered_rock',
        depthTop: 18.0,
        depthBottom: 26.0,
        unitWeight: 21.0,
        satUnitWeight: 22.0,
        cohesion: 50,
        frictionAngle: 38,
        subgradeReactionKh: 80000,
        permeabilityK: 1e-5,
        color: '#8D6E63',
        nValue: 50,
      },
      {
        id: 'l5',
        name: '연암~보통암 (Rock)',
        type: 'hard_rock',
        depthTop: 26.0,
        depthBottom: 42.0,
        unitWeight: 24.0,
        satUnitWeight: 25.0,
        cohesion: 200,
        frictionAngle: 42,
        subgradeReactionKh: 250000,
        permeabilityK: 1e-7,
        color: '#455A64',
        nValue: 50,
      },
    ],
    wall: {
      type: 'DIAPHRAGM_WALL',
      name: '지하연속벽 (Slurry Wall t=800mm 콘크리트 fck=30MPa)',
      totalLength: 38.0,
      embedmentDepth: 6.0,
      pileSpacing: 1.0,
      elasticModulusE: 28000,
      momentOfInertiaI: 4266666, // cm4/m (t=0.8m wall)
      sectionModulusZ: 106666, // cm³/m
      crossSectionAreaA: 8000, // cm²/m
      allowableBendingStress: 18, // MPa (철근콘크리트 허용압축응력)
      allowableShearStress: 2.5, // MPa
      corrosionAllowance: 0,
      description: '차수성과 고강성을 보유한 800mm 두께 RC 지하연속벽',
    },
    struts: [
      {
        id: 'gtx-s1',
        tier: 1,
        depth: 2.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ711.2×14t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 30.0,
        crossSectionAreaA: 306.6,
        momentOfInertiaI: 187000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 2,
      },
      {
        id: 'gtx-s2',
        tier: 2,
        depth: 7.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ711.2×16t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 45.0,
        crossSectionAreaA: 349.3,
        momentOfInertiaI: 211000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 4,
      },
      {
        id: 'gtx-s3',
        tier: 3,
        depth: 13.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ812.8×16t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 60.0,
        crossSectionAreaA: 400.4,
        momentOfInertiaI: 320000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-450×400×14×26',
        waleZ: 8500,
        waleAllowableBending: 210,
        installedAtStep: 6,
      },
      {
        id: 'gtx-s4',
        tier: 4,
        depth: 18.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ812.8×18t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 70.0,
        crossSectionAreaA: 449.5,
        momentOfInertiaI: 357000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-450×400×14×26',
        waleZ: 8500,
        waleAllowableBending: 210,
        installedAtStep: 8,
      },
      {
        id: 'gtx-s5',
        tier: 5,
        depth: 24.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ812.8×18t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 75.0,
        crossSectionAreaA: 449.5,
        momentOfInertiaI: 357000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-450×400×14×26',
        waleZ: 8500,
        waleAllowableBending: 210,
        installedAtStep: 10,
      },
      {
        id: 'gtx-s6',
        tier: 6,
        depth: 28.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ812.8×20t',
        horizontalSpacing: 4.5,
        excavationWidth: 26.0,
        hasCenterPost: true,
        preloadTon: 80.0,
        crossSectionAreaA: 498.1,
        momentOfInertiaI: 393000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-450×400×14×26',
        waleZ: 8500,
        waleAllowableBending: 210,
        installedAtStep: 12,
      },
    ],
    stages: [
      { step: 0, name: '초기상태 (가이드월 및 슬러리월 시공 완료)', excavationDepth: 0.0, activeStrutIds: [], description: '지하연속벽 38.0m 시공 및 지표 복공 설치', isCompleted: false },
      { step: 1, name: '1차 굴착 (GL -3.0m)', excavationDepth: 3.0, activeStrutIds: [], description: '1단 지보 가설 깊이까지 굴착', isCompleted: false },
      { step: 2, name: '1단 버팀보 가설 (GL -2.5m)', excavationDepth: 3.0, activeStrutIds: ['gtx-s1'], description: '1단 스트럿 설치 및 선하중 30t 재하', isCompleted: false },
      { step: 3, name: '2차 굴착 (GL -8.0m)', excavationDepth: 8.0, activeStrutIds: ['gtx-s1'], description: '점토층 통과 굴착 진행', isCompleted: false },
      { step: 4, name: '2단 버팀보 가설 (GL -7.5m)', excavationDepth: 8.0, activeStrutIds: ['gtx-s1', 'gtx-s2'], description: '2단 스트럿 설치 및 선하중 45t 재하', isCompleted: false },
      { step: 5, name: '3차 굴착 (GL -13.5m)', excavationDepth: 13.5, activeStrutIds: ['gtx-s1', 'gtx-s2'], description: '모래자갈 대수층 굴착', isCompleted: false },
      { step: 6, name: '3단 버팀보 가설 (GL -13.0m)', excavationDepth: 13.5, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3'], description: '3단 대구경 스트럿 가설 및 선하중 60t 재하', isCompleted: false },
      { step: 7, name: '4차 굴착 (GL -19.0m)', excavationDepth: 19.0, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3'], description: '풍화암층 상부 진입', isCompleted: false },
      { step: 8, name: '4단 버팀보 가설 (GL -18.5m)', excavationDepth: 19.0, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4'], description: '4단 스트럿 가설 및 선하중 70t 재하', isCompleted: false },
      { step: 9, name: '5차 굴착 (GL -24.5m)', excavationDepth: 24.5, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4'], description: '풍화암층 굴착', isCompleted: false },
      { step: 10, name: '5단 버팀보 가설 (GL -24.0m)', excavationDepth: 24.5, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4', 'gtx-s5'], description: '5단 스트럿 가설 및 선하중 75t 재하', isCompleted: false },
      { step: 11, name: '6차 굴착 (GL -29.0m)', excavationDepth: 29.0, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4', 'gtx-s5'], description: '연암층 진입 굴착', isCompleted: false },
      { step: 12, name: '6단 버팀보 가설 (GL -28.5m)', excavationDepth: 29.0, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4', 'gtx-s5', 'gtx-s6'], description: '최하단 6단 스트럿 가설 및 선하중 80t', isCompleted: false },
      { step: 13, name: '최종 바닥 굴착 완료 (GL -32.0m)', excavationDepth: 32.0, activeStrutIds: ['gtx-s1', 'gtx-s2', 'gtx-s3', 'gtx-s4', 'gtx-s5', 'gtx-s6'], description: '대심도 GTX 역사 바닥 저판면 GL -32.0m 도달', isCompleted: false },
    ],
  },
  {
    id: 'cip_waterfront_station',
    title: '하천 인접 지하 2층 정거장 (CIP 주열벽)',
    subtitle: 'CIP(Cast-In-Place) + 차수그라우팅 + 4단 버팀보 (심도 17.5m, 폭 18.0m)',
    category: '하천인접/차수형',
    description: '하천이나 지하수위가 높은 구간에서 토류판 틈새 모래 유출 및 보일링을 방지하기 위해 CIP 연속 주열벽(Φ500@450)과 배면 LW/JSP 차수그라우팅을 조합한 단면입니다.',
    settings: {
      projectName: '00천 통과구간 지하 2층 정거장 가시설',
      stationName: '수변공원역',
      location: '하천변 인접 6차선 도로',
      roadWidth: 28.0,
      stationWidth: 18.0,
      stationLength: 120.0,
      finalExcavationDepth: 17.5,
      groundWaterTable: 2.5,
      surchargeLoad: 10.0,
      earthPressureTheory: 'PECK',
      seismicCoefficient: 0.12,
      deckHouseLoad: 4.5,
    },
    layers: [
      {
        id: 'c-l1',
        name: '매립토 (Fill)',
        type: 'fill',
        depthTop: 0,
        depthBottom: 3.0,
        unitWeight: 17.5,
        satUnitWeight: 18.5,
        cohesion: 5,
        frictionAngle: 28,
        subgradeReactionKh: 12000,
        permeabilityK: 1e-3,
        color: '#D7CCC8',
        nValue: 7,
      },
      {
        id: 'c-l2',
        name: '자갈섞인 조립모래 (Gravelly Sand)',
        type: 'sand',
        depthTop: 3.0,
        depthBottom: 9.0,
        unitWeight: 19.0,
        satUnitWeight: 20.0,
        cohesion: 0,
        frictionAngle: 34,
        subgradeReactionKh: 28000,
        permeabilityK: 1e-2,
        color: '#FFE082',
        nValue: 26,
      },
      {
        id: 'c-l3',
        name: '풍화토 (Weathered Soil)',
        type: 'weathered_soil',
        depthTop: 9.0,
        depthBottom: 15.0,
        unitWeight: 19.5,
        satUnitWeight: 20.5,
        cohesion: 15,
        frictionAngle: 32,
        subgradeReactionKh: 40000,
        permeabilityK: 1e-4,
        color: '#BCAAA4',
        nValue: 38,
      },
      {
        id: 'c-l4',
        name: '풍화암 (Weathered Rock)',
        type: 'weathered_rock',
        depthTop: 15.0,
        depthBottom: 25.0,
        unitWeight: 22.0,
        satUnitWeight: 23.0,
        cohesion: 60,
        frictionAngle: 38,
        subgradeReactionKh: 100000,
        permeabilityK: 1e-6,
        color: '#8D6E63',
        nValue: 50,
      },
    ],
    wall: {
      type: 'CIP',
      name: 'CIP 주열벽 (Φ500 @450mm H-300×300 삽입)',
      totalLength: 23.0,
      embedmentDepth: 5.5,
      pileSpacing: 0.9,
      elasticModulusE: 205000,
      momentOfInertiaI: 40800,
      sectionModulusZ: 2720,
      crossSectionAreaA: 172.0,
      allowableBendingStress: 210,
      allowableShearStress: 120,
      corrosionAllowance: 0.5,
      description: '현장타설말뚝(CIP) 내 H-형강 삽입 및 연속 시공으로 차수성 확보',
    },
    struts: [
      {
        id: 'cip-s1',
        tier: 1,
        depth: 2.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ508×9.5t',
        horizontalSpacing: 3.5,
        excavationWidth: 18.0,
        hasCenterPost: true,
        preloadTon: 15.0,
        crossSectionAreaA: 148.8,
        momentOfInertiaI: 46200,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-300×300×10×15',
        waleZ: 2720,
        waleAllowableBending: 210,
        installedAtStep: 2,
      },
      {
        id: 'cip-s2',
        tier: 2,
        depth: 6.0,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ508×11t',
        horizontalSpacing: 3.5,
        excavationWidth: 18.0,
        hasCenterPost: true,
        preloadTon: 25.0,
        crossSectionAreaA: 171.8,
        momentOfInertiaI: 52900,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-350×350×12×19',
        waleZ: 4600,
        waleAllowableBending: 210,
        installedAtStep: 4,
      },
      {
        id: 'cip-s3',
        tier: 3,
        depth: 10.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×12t',
        horizontalSpacing: 3.5,
        excavationWidth: 18.0,
        hasCenterPost: true,
        preloadTon: 35.0,
        crossSectionAreaA: 225.3,
        momentOfInertiaI: 99400,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-350×350×12×19',
        waleZ: 4600,
        waleAllowableBending: 210,
        installedAtStep: 6,
      },
      {
        id: 'cip-s4',
        tier: 4,
        depth: 14.5,
        type: 'PIPE_STRUT',
        specName: '강관 버팀보 Φ609.6×14t',
        horizontalSpacing: 3.5,
        excavationWidth: 18.0,
        hasCenterPost: true,
        preloadTon: 40.0,
        crossSectionAreaA: 262.0,
        momentOfInertiaI: 114000,
        elasticModulusE: 205000,
        allowableAxialStress: 160,
        waleSpecName: '2H-400×400×13×21',
        waleZ: 6660,
        waleAllowableBending: 210,
        installedAtStep: 8,
      },
    ],
    stages: [
      { step: 0, name: 'CIP 주열벽 및 차수그라우팅 시공', excavationDepth: 0.0, activeStrutIds: [], description: '수변공원 인접 도로 복공 완료', isCompleted: false },
      { step: 1, name: '1차 굴착 (GL -2.5m)', excavationDepth: 2.5, activeStrutIds: [], description: '1단 띠장 시공면까지 굴착', isCompleted: false },
      { step: 2, name: '1단 버팀보 가설 (GL -2.0m)', excavationDepth: 2.5, activeStrutIds: ['cip-s1'], description: '1단 Φ508 강관 설치 및 15t 선하중', isCompleted: false },
      { step: 3, name: '2차 굴착 (GL -6.5m)', excavationDepth: 6.5, activeStrutIds: ['cip-s1'], description: '고수위 모래층 굴착 및 차수벽 상태 확인', isCompleted: false },
      { step: 4, name: '2단 버팀보 가설 (GL -6.0m)', excavationDepth: 6.5, activeStrutIds: ['cip-s1', 'cip-s2'], description: '2단 Φ508 강관 설치 및 25t 선하중', isCompleted: false },
      { step: 5, name: '3차 굴착 (GL -11.0m)', excavationDepth: 11.0, activeStrutIds: ['cip-s1', 'cip-s2'], description: '풍화토층 굴착', isCompleted: false },
      { step: 6, name: '3단 버팀보 가설 (GL -10.5m)', excavationDepth: 11.0, activeStrutIds: ['cip-s1', 'cip-s2', 'cip-s3'], description: '3단 Φ609.6 강관 설치 및 35t 선하중', isCompleted: false },
      { step: 7, name: '4차 굴착 (GL -15.0m)', excavationDepth: 15.0, activeStrutIds: ['cip-s1', 'cip-s2', 'cip-s3'], description: '풍화암층 출현', isCompleted: false },
      { step: 8, name: '4단 버팀보 가설 (GL -14.5m)', excavationDepth: 15.0, activeStrutIds: ['cip-s1', 'cip-s2', 'cip-s3', 'cip-s4'], description: '4단 Φ609.6 강관 설치 및 40t 선하중', isCompleted: false },
      { step: 9, name: '최종 바닥 굴착 완료 (GL -17.5m)', excavationDepth: 17.5, activeStrutIds: ['cip-s1', 'cip-s2', 'cip-s3', 'cip-s4'], description: '정거장 기초 저판면 도달', isCompleted: false },
    ],
  },
];
